apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: example-app-dev-stage
  namespace: team2-dev
spec:
  chart:
    git: https://github.com/nniikkoollaaii/GitOps_K8s_Cluster_via_Terraform_Config_Team2_Helm
    path: "example"
    ref: develop
    secretRef: 
      name: "git-auth"
    releaseName: example-app-dev-stage
    version: 1.0.0
    targetNamespace: team2-develop